---
# Setup playbook for lightweight container orchestration infrastructure
# This playbook prepares hosts for container orchestration

- name: Setup container hosts
  hosts: container_hosts
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
    
    - name: Install basic dependencies
      package:
        name:
          - curl
          - wget
          - git
          - net-tools
        state: present
    
    - name: Ensure required directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/orchestration
        - /var/log/orchestration
    
    - name: Display setup completion message
      debug:
        msg: "Host {{ inventory_hostname }} has been prepared for container orchestration"
