apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: lightweight-orchestration
data:
  app.properties: |
    environment=production
    log_level=info
    max_connections=100
  nginx.conf: |
    worker_processes auto;
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }
    }
