---
# Ansible Galaxy requirements
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  # Community general collection for various modules
  - name: community.general
    version: ">=8.0.0"
  
  # Docker collection for container management
  - name: community.docker
    version: ">=3.4.0"

# Add role dependencies if needed
# roles:
#   - name: geerlingguy.docker
#     version: "7.0.0"
